### ISSUE TITLE
大佬，请问这个插件可以上架到商店吗

### ISSUE THREAD

**Issue by munderline** [JimmyTinsley/jsproxy-firefox-extension#1]
现在用的是debug模式下的临时加载，每次都要重新加载一次，比较麻烦。。。

**Comment by JimmyTinsley** [comment]
不好意思现在才看到issue! 

我尝试上架一下, 因为之前都只是自用所以没往上架那方面想😂

**Comment by munderline** [comment]
前几天我自己摸索着在AMO上签名了，没有公开我也是自用，有了签名之后不用每次都重新加载了，插件很好，给大佬点赞

**Comment by JimmyTinsley** [comment]
https://addons.mozilla.org/en-US/firefox/addon/jsproxy-extension/
你好, 插件上架成功了

**Comment by munderline** [comment]
> https://addons.mozilla.org/en-US/firefox/addon/jsproxy-extension/
> 你好, 插件上架成功了
谢谢大佬，已经用上了

**Comment by JimmyTinsley** [comment]
@munderline 不客气😊
